{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/LocalizedError-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/auth0\/managementerror\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:5Auth015ManagementErrorV","extendedModule":"Foundation","role":"symbol","modules":[{"relatedModules":["Foundation"],"name":"Auth0"}],"symbolKind":"property","platforms":[{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"deprecated":false,"introducedAt":"10.10","name":"macOS","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0","beta":false},{"name":"watchOS","deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false}],"title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/recoverySuggestion","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.auth0.Auth0/documentation/Auth0/ManagementError/LocalizedError-Implementations":{"kind":"article","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/LocalizedError-Implementations","abstract":[],"type":"topic","url":"\/documentation\/auth0\/managementerror\/localizederror-implementations","title":"LocalizedError Implementations","role":"collectionGroup"},"doc://com.auth0.Auth0/documentation/Auth0":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","url":"\/documentation\/auth0","type":"topic","role":"collection","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}]},"doc://com.auth0.Auth0/documentation/Auth0/ManagementError":{"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Management API v2."}],"title":"ManagementError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ManagementError","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/auth0\/managementerror","navigatorTitle":[{"text":"ManagementError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError"},"doc://com.auth0.Auth0/documentation/Auth0/ManagementError/recoverySuggestion":{"url":"\/documentation\/auth0\/managementerror\/recoverysuggestion","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/recoverySuggestion","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","title":"recoverySuggestion"}}}