{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/auth0\/managementerror\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/recoverySuggestion","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"recoverySuggestion","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:5Auth015ManagementErrorV","extendedModule":"Foundation","modules":[{"name":"Auth0"}]},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/LocalizedError-Implementations"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/ManagementError/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/managementerror\/recoverysuggestion"},"doc://com.auth0.Auth0/documentation/Auth0/ManagementError":{"role":"symbol","title":"ManagementError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementError"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Management API v2."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementError"}],"url":"\/documentation\/auth0\/managementerror"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","title":"Auth0","abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","type":"topic","url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/ManagementError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/ManagementError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/auth0\/managementerror\/localizederror-implementations"}}}