{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true,"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"Auth0"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"title":"Auth0","role":"collection","type":"topic","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"role":"symbol","url":"\/documentation\/auth0\/authenticationerror\/failurereason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","title":"failureReason","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","abstract":[]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents an error during a request to the Auth0 Authentication API.","type":"text"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","url":"\/documentation\/auth0\/authenticationerror","role":"symbol","title":"AuthenticationError"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","title":"recoverySuggestion","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","abstract":[],"kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","title":"helpAnchor","url":"\/documentation\/auth0\/authenticationerror\/helpanchor","abstract":[],"kind":"symbol"}}}