{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"Auth0"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true}],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"url":"\/documentation\/auth0\/authenticationerror","type":"topic","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"title":"AuthenticationError","abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"url":"\/documentation\/auth0\/authenticationerror\/helpanchor","type":"topic","kind":"symbol","title":"helpAnchor","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[]},"doc://com.auth0.Auth0/documentation/Auth0":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","url":"\/documentation\/auth0","type":"topic","role":"collection","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","type":"topic","kind":"symbol","title":"recoverySuggestion","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"url":"\/documentation\/auth0\/authenticationerror\/failurereason","type":"topic","kind":"symbol","title":"failureReason","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[]}}}