{"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Auth0"}],"title":"LocalizedError Implementations","role":"collectionGroup"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"]}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"kind":"article","references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"failureReason","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/failurereason","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","title":"recoverySuggestion","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","title":"AuthenticationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"url":"\/documentation\/auth0\/authenticationerror"},"doc://com.auth0.Auth0/documentation/Auth0":{"url":"\/documentation\/auth0","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"title":"helpAnchor","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/helpanchor","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]}}}