{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"kind":"article","metadata":{"modules":[{"name":"Auth0"}],"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","type":"topic","url":"\/documentation\/auth0\/authenticationerror\/failurereason"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"recoverySuggestion","role":"symbol","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","abstract":[]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/auth0\/authenticationerror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"title":"AuthenticationError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","kind":"symbol","type":"topic","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","type":"topic","abstract":[],"title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/auth0\/authenticationerror\/helpanchor","kind":"symbol"}}}