{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"]}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Auth0"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"sections":[],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true,"title":"Instance Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"url":"\/documentation\/auth0\/authenticationerror\/helpanchor","role":"symbol","abstract":[],"title":"helpAnchor","type":"topic","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"type":"topic","title":"recoverySuggestion","abstract":[],"kind":"symbol","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","type":"topic","title":"Auth0","url":"\/documentation\/auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","abstract":[{"text":"SDK for Apple platforms.","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"title":"AuthenticationError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"url":"\/documentation\/auth0\/authenticationerror","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"failureReason","url":"\/documentation\/auth0\/authenticationerror\/failurereason","role":"symbol","type":"topic","kind":"symbol"}}}