{"metadata":{"role":"collectionGroup","title":"Auth0Error Implementations","modules":[{"name":"Auth0"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"sections":[],"kind":"article","identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","kind":"symbol","abstract":[{"type":"text","text":"Description of the error."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","title":"errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialsManagerError"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}],"title":"CredentialsManagerError"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"title":"localizedDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Description of the error.","type":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription"},"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"role":"collection","url":"\/documentation\/auth0","kind":"symbol"}}}