{"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"title":"Instance Properties"}],"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"Auth0"}],"roleHeading":"API Collection","title":"Auth0Error Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"url":"\/documentation\/auth0\/credentialsmanagererror","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","role":"symbol","kind":"symbol","type":"topic","title":"CredentialsManagerError","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"kind":"symbol","title":"localizedDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","role":"symbol","type":"topic","abstract":[{"text":"Description of the error.","type":"text"}],"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"abstract":[{"type":"text","text":"Description of the error."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","title":"errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0":{"kind":"symbol","url":"\/documentation\/auth0","role":"collection","title":"Auth0","type":"topic","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0"}}}