{"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/cause-6z721","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription-19uqs","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription-bz71"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Auth0"}],"role":"collectionGroup","title":"Auth0Error Implementations"},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","title":"Auth0","abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","type":"topic","url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription-19uqs":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Description of the error."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription-19uqs","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription-19uqs"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"role":"symbol","title":"CredentialsManagerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialsManagerError"}],"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}],"url":"\/documentation\/auth0\/credentialsmanagererror"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/cause-6z721":{"role":"symbol","title":"cause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" value, if any. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/cause-6z721","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/cause-6z721"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription-bz71":{"role":"symbol","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Description of the error."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription-bz71","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription-bz71"}}}