{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"sections":[],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Auth0Error Implementations","modules":[{"name":"Auth0"}]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"title":"CredentialsManagerError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"title":"localizedDescription","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Description of the error."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","kind":"symbol","type":"topic","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","abstract":[{"text":"Description of the error.","type":"text"}],"role":"symbol","kind":"symbol"}}}