{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"title":"noCredentials","roleHeading":"Type Property","modules":[{"name":"Auth0"}]},"abstract":[{"text":"No credentials were found in the store.","type":"text"},{"text":" ","type":"text"},{"text":"This error does not include a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}]}]}],"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"abstract":[{"text":"No credentials were found in the store.","type":"text"},{"text":" ","type":"text"},{"text":"This error does not include a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","type":"reference"},{"text":".","type":"text"}],"title":"noCredentials","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError"}]},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","url":"\/documentation\/auth0","kind":"symbol","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"type":"topic","title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"title":"cause","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","url":"\/documentation\/auth0\/auth0error\/cause-9wuyi","role":"symbol","abstract":[{"text":"The underlying ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" value, if any. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"url":"\/documentation\/auth0\/credentialsmanagererror","type":"topic","kind":"symbol","title":"CredentialsManagerError"}}}