{"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials"},"metadata":{"externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ","roleHeading":"Type Property","symbolKind":"property","title":"noCredentials","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"noCredentials","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CredentialsManagerError","kind":"typeIdentifier","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"modules":[{"name":"Auth0"}],"role":"symbol"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"abstract":[{"text":"No credentials were found in the store.","type":"text"},{"text":" ","type":"text"},{"text":"This error does not include a ","type":"text"},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","type":"reference","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noCredentials"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","title":"Auth0","url":"\/documentation\/auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","role":"collection","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cause","kind":"identifier"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","title":"cause","url":"\/documentation\/auth0\/auth0error\/cause-9wuyi","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"Error"},{"text":" value, if any. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"topic"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"kind":"symbol","title":"noCredentials","abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"title":"CredentialsManagerError","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}]}}}