{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"noCredentials","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CredentialsManagerError","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"text":"This error does not include a ","type":"text"},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","type":"reference","isActive":true},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","metadata":{"title":"noCredentials","externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ","role":"symbol","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"noCredentials","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"modules":[{"name":"Auth0"}],"roleHeading":"Type Property"},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"kind":"symbol","title":"noCredentials","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"No credentials were found in the store.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials"},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"kind":"symbol","title":"cause","url":"\/documentation\/auth0\/auth0error\/cause-9wuyi","type":"topic","abstract":[{"type":"text","text":"The underlying "},{"code":"Error","type":"codeVoice"},{"type":"text","text":" value, if any. Defaults to "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cause","kind":"identifier"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CredentialsManagerError","kind":"identifier"}],"navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"url":"\/documentation\/auth0\/credentialsmanagererror","title":"CredentialsManagerError","role":"symbol","type":"topic"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","title":"Auth0"}}}