{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV","text":"CredentialsManagerError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/auth0\/credentialsmanagererror\/nocredentials"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"title":"noCredentials","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:5Auth023CredentialsManagerErrorV02noB0ACvpZ","modules":[{"name":"Auth0"}]},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"references":{"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"role":"symbol","title":"CredentialsManagerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialsManagerError"}],"abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}],"url":"\/documentation\/auth0\/credentialsmanagererror"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","title":"Auth0","abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","type":"topic","url":"\/documentation\/auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/noCredentials":{"role":"symbol","title":"noCredentials","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CredentialsManagerError","preciseIdentifier":"s:5Auth023CredentialsManagerErrorV"}],"abstract":[{"type":"text","text":"No credentials were found in the store."},{"type":"text","text":" "},{"type":"text","text":"This error does not include a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/noCredentials","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/credentialsmanagererror\/nocredentials"},"doc://com.auth0.Auth0/documentation/Auth0/Auth0Error/cause-9wuyi":{"role":"symbol","title":"cause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The underlying "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" value, if any. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/Auth0Error\/cause-9wuyi","kind":"symbol","type":"topic","url":"\/documentation\/auth0\/auth0error\/cause-9wuyi"}}}